### ISSUE TITLE
【疑问】这样的回答真的不会误导别人么

### ISSUE THREAD

**Issue by Zheaoli** [kenwoodjw/python_interview_question#10]
![image](https://user-images.githubusercontent.com/7054676/53797886-143eea80-3f72-11e9-9b06-1e8add83b842.png)

**Comment by kenwoodjw** [comment]
nginx最大并发5w没问题，django，c10k问题，可能不是很严谨

**Comment by Zheaoli** [comment]
1. Django 在机器配置足够的情况下，能抗的 QPS 远不止 10k

2. 高并发不是 Django 的事，是体系的事

3. 性能问题主流的解决方案也不是你这么玩的。socket 直接 Gevent patch（也有很多副作用）至于底层用 C/C++ 重写，是多底层？

4. Django/Flask/Tornado 跟前后分离都没什么关系

5. ORM 生成的 SQL 比自己手写的高很多了，多表也不一定用外键。

6. Tornado 恕我直言，周边差，并不是理想框架。而且性能取决于你的部署方案
