### ISSUE TITLE
[吐槽] #1.1 错得最离谱的一题

### ISSUE THREAD

**Issue by Pandaaaa906** [kenwoodjw/python_interview_question#19]
[#1.1](https://github.com/kenwoodjw/python_interview_question#11-%E6%9C%89%E4%B8%80%E4%B8%AAjsonline%E6%A0%BC%E5%BC%8F%E7%9A%84%E6%96%87%E4%BB%B6filetxt-%E5%A4%A7%E5%B0%8F%E7%BA%A6%E4%B8%BA10k)
第一个案例这个答案为啥要append啊，循环里yield eachline，不就好了吗，这不多此一举吗。。。
第二个案例这个答案是搞笑的吧？根本就是错的。。。
1. readlines返回的是列表，你append到另外一个list，
2. 其实py3里面，for i in f已经是stream了，
2. 最后你还yield？
其实10G的文本读写除了for in ，还可以用mmap啊，

**Comment by kenwoodjw** [comment]
写法不够简洁

**Comment by Pandaaaa906** [comment]
> 写法不够简洁

没明白写法不够简洁是什么意思。。。
这是第一个案例~
```python
def get_lines(fp):
    with open(fp,'rb') as f:
        for line in f:
            yield line
```
这是第二个案例 用mmap~
```python
from mmap import mmap


def get_lines(fp):
    with open(fp,"r+") as f:
        m = mmap(f.fileno(), 0)
        tmp = 0
        for i, char in enumerate(m):
            if char==b"\n":
                yield m[tmp:i+1].decode()
                tmp = i+1

if __name__=="__main__":
    for i in get_lines("fp_some_huge_file"):
        print(i)
```
而且你第一题的代码漏了个单引号~
