### ISSUE TITLE
1.文件操作，这样是否可以？

### ISSUE THREAD

**Issue by XingDongZhe** [kenwoodjw/python_interview_question#49]
def get_lines():
    with open('file.txt','rb') as f:
        records = iter(partial(file.read,4096),b'')
        for r in records:
            yield r.decode('utf-8')

if __name__ == '__main__':
    for e in get_lines():
        process(e) # 处理每一行数据

**Comment by nasyxx** [comment]
先不说 上面 `as f` 下面是 `file.read` 。

如果有一行的长度超过 4096 怎么办？

把代码弄成代码块，弄好缩进，检查好有没有基本的语法错误再...
