### ISSUE TITLE
9.请按alist中元素的age由大到小排序

### ISSUE THREAD

**Issue by XingDongZhe** [kenwoodjw/python_interview_question#50]
使用itemgetter 更优雅

from operator import itemgetter
alist = [{'name': 'a', 'age': 20}, {'name': 'b', 'age': 30}, {'name': 'c', 'age': 25}]
alist_sorted = sorted(alist, key=itemgetter('age'), reverse=True)

**Comment by kenwoodjw** [comment]
可以提交pr
