### ISSUE TITLE
3.4 SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by heiretodemon** [kenwoodjw/python_interview_question#52]
3.4给的答案有问题
for iterms in str1.split('|'):
      key, value = iterms.split(':'):
             dict1[key] = value
iterms.split(':')后面就不应该有冒号了，下一行的存进dict1操作应该是依次进行的，而不是在它下一级，去掉冒号少一级缩进就OK了

**Comment by nasyxx** [comment]
(乃是不是在看着老版本的...

**Comment by heiretodemon** [comment]
额，那新版本的在哪里




------------------ 原始邮件 ------------------
发件人: "Nasy"<notifications@github.com>;
发送时间: 2019年4月7日(星期天) 上午9:50
收件人: "kenwoodjw/python_interview_question"<python_interview_question@noreply.github.com>;
抄送: "171982919"<171982919@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [kenwoodjw/python_interview_question] 3.4 SyntaxError: invalidsyntax (#52)




(乃是不是在看着老版本的...

**Comment by nasyxx** [comment]
就是项目的 readme 嘛..
<img width="854" alt="Screen Shot 2019-04-07 at 20 26 35" src="https://user-images.githubusercontent.com/5007613/55683540-7e80eb80-5973-11e9-98fb-9b261fb34fc1.png">

**Comment by heiretodemon** [comment]
哦才注意到，看来我fork后你们又更新了。。。




------------------ 原始邮件 ------------------
发件人: "Nasy"<notifications@github.com>;
发送时间: 2019年4月7日(星期天) 晚上8:27
收件人: "kenwoodjw/python_interview_question"<python_interview_question@noreply.github.com>;
抄送: "171982919"<171982919@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [kenwoodjw/python_interview_question] 3.4 SyntaxError: invalidsyntax (#52)




就是项目的 readme 嘛..
