### ISSUE TITLE
GIL锁不是只有CPython才有

### ISSUE THREAD

**Issue by AirDu** [kenwoodjw/python_interview_question#58]
`Jython`确实没有，但`PyPy`依然存在`GIL`，下面引用一段[PyPy官方文档](http://doc.pypy.org/en/latest/faq.html#does-pypy-have-a-gil-why)的内容：

> **Does PyPy have a GIL? Why?**
> 
> Yes, PyPy has a GIL. Removing the GIL is very hard. On top of CPython, you have two problems: (1) GC, in this case reference counting; (2) the whole Python language.   
> 
> For PyPy, the hard issue is (2): by that I mean issues like what occurs if a mutable object is changed from one thread and read from another concurrently. This is a problem for any mutable type: it needs careful review and fixes (fine-grained locks, mostly) through the whole Python interpreter. It is a major effort, although not completely impossible, as Jython/IronPython showed. This includes subtle decisions about whether some effects are ok or not for the user (i.e. the Python programmer).
> 
> CPython has additionally the problem (1) of reference counting. With PyPy, this sub-problem is simpler: we need to make our GC multithread-aware. This is easier to do efficiently in PyPy than in CPython. It doesn’t solve the issue (2), though.
> 
> Note that since 2012 there is work going on on a still very experimental Software Transactional Memory (STM) version of PyPy. This should give an alternative PyPy which works without a GIL, while at the same time continuing to give the Python programmer the complete illusion of having one. This work is currently a bit stalled because of its own technical difficulties.

**Comment by AirDu** [comment]
`113.什么是死锁？` 这节里有写：
> GIL锁 全局解释器锁（只在cython里才有）

**Comment by nasyxx** [comment]
乃应该直接提 pull request （

**Comment by kenwoodjw** [comment]
没怎么关注pypy
